baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Léo'

theme = "PaperMod"

defaultContentLanguage = "fr"
defaultContentLanguageInSubdir = true

[languages]
  [languages.fr]
    languageName = "Français"
    weight = 1

  [languages.en]
    languageName = "English"
    weight = 2
