baseURL = 'https://leo.angonnet.tf'
languageCode = 'en-us'
title = 'Léo'
copyright = '2025'

theme = "PaperMod"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

buildDrafts = false
buildFuture = true
enableEmoji = true

mainsections = ["posts"]

[pagination]
disableAliases = false
pagerSize = 5

[languages.en]
languageName = ":uk:"
weight = 1
contentDir = 'content/en'

[languages.fr]
languageName = ":fr:"
weight = 2
contentDir = 'content/fr'

[languages.en.taxonomies]
category = "categories"
tag = "tags"
series = "series"
[languages.fr.taxonomies]
category = "categories"
tag = "tags"
search = "recherche"
# series = "series"

[languages.fr.params]
languageAltTitle = "French"

[params.profileMode]
enabled = true
title = "Léo Angonnet"
# imageUrl = "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
# imageTitle = "ProfileMode image"
# imageWidth = 120
# imageHeight = 120
subtitle = "CS engineering student at [<u>UTBM</u>](https://utbm.fr), focused on networks, virtualization & security | Dev & self-hosting enthusiast"
[languages.fr.params.profileMode]
enabled = true
title = "Léo Angonnet"
subtitle = "Étudiant en informatique à l'[<u>UTBM</u>](https://utbm.fr), spécialisé en réseaux, virtualisation et sécurité | Ayant un intérêt pour le développement et l'auto-hébergement"

[[params.profileMode.buttons]]
name = "Projects"
url = "posts"
[[languages.fr.params.profileMode.buttons]]
name = "Projets"
url = "posts"

[[menu.main]]
name = "Search"
url = "search/"
weight = 5
[[languages.fr.menu.main]]
name = "Recherche"
url = "search/"
weight = 5

[[menu.main]]
name = "Archives"
url = "archives"
weight = 10
[[languages.fr.menu.main]]
name = "Archives"
url = "archives"
weight = 10

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 15
[[languages.fr.menu.main]]
name = "Catégories"
url = "tags/"
weight = 15

[params]
defaultTheme = "auto"
# disableThemeToggle = true
# ShowShareButtons = true
ShowReadingTime = true
# disableSpecial1stPost = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
# ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = true
# comments = false
# images = ["images/papermod-cover.png"]

[[params.socialIcons]]
name = "github"
title = "Github profile"
url = "https://github.com/langonne"

[[params.socialIcons]]
name = "linkedin"
title = "Linkedin profile"
url = "https://www.linkedin.com/in/l%C3%A9o-angonnet/"

[[params.socialIcons]]
name = "email"
title = "Send mail"
url = "mailto:leo.angonnet@ik.me"

# [params.editPost]
# URL = "https://github.com/adityatelange/hugo-PaperMod/tree/exampleSite/content"
# Text = "Suggest Changes"
# appendFilePath = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
# anchorLineNos = true
# codeFences = true
# guessSyntax = true
# lineNos = true
# style = "monokai"
